on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - id: stringSha
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.sha }}
    - id: stringRepo
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.repository }}
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ steps.stringRepo.outputs.lowercase }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ steps.stringSha.outputs.lowercase }}